///Name(M/F,First/Last/Full);
/// @description Create 1d arrays for male and female names
/// @param M/F
/// @param First/Last/Full

var MName = [];
var FName = [];
var LName = [];

MName[0] = "Isaac";
FName[0] = "Isabelle";
MName[1] = "James";
FName[1] = "Mary";
MName[2] = "John";
FName[2] = "Patricia";
MName[3] = "Robert";
FName[3] = "Jennifer";
MName[4] = "Michael";
FName[4] = "Elizabeth";
MName[5] = "William";
FName[5] = "Linda";
MName[6] = "David";
FName[6] = "Barbara";
MName[7] = "Richard";
FName[7] = "Susan";
MName[8] = "Joseph";
FName[8] = "Jessica";
MName[9] = "Thomas";
FName[9] = "Margaret";
MName[10] = "Charles";
FName[10] = "Sarah";
MName[11] = "Christopher";
FName[11] = "Karen";
MName[12] = "Daniel";
FName[12] = "Nancy";
MName[13] = "Matthew";
FName[13] = "Betty";
MName[14] = "Anthony";
FName[14] = "Lisa";
MName[15] = "Donald";
FName[15] = "Dorothy";
MName[16] = "Mark";
FName[16] = "Sandra";
MName[17] = "Paul";
FName[17] = "Ashley";
MName[18] = "Steven";
FName[18] = "Kimberly";
MName[19] = "Andrew";
FName[19] = "Donna";
MName[20] = "Kenneth";
FName[20] = "Carol";
MName[21] = "George";
FName[21] = "Michelle";
MName[22] = "Joshua";
FName[22] = "Emily";
MName[23] = "Kevin";
FName[23] = "Amanda";
MName[24] = "Brian";
FName[24] = "Helen";
MName[25] = "Edward";
FName[25] = "Melissa";
MName[26] = "Ronald";
FName[26] = "Deborah";
MName[27] = "Timothy";
FName[27] = "Stephanie";
MName[28] = "Jason";
FName[28] = "Laura";
MName[29] = "Jeffrey";
FName[29] = "Rebecca";
MName[30] = "Ryan";
FName[30] = "Sharon";
MName[31] = "Gary";
FName[31] = "Cynthia";
MName[32] = "Jacob";
FName[32] = "Kathleen";
MName[33] = "Nicholas";
FName[33] = "Amy";
MName[34] = "Eric";
FName[34] = "Shirley";
MName[35] = "Stephen";
FName[35] = "Anna";
MName[36] = "Jonathan";
FName[36] = "Angela";
MName[37] = "Larry";
FName[37] = "Ruth";
MName[38] = "Justin";
FName[38] = "Brenda";
MName[39] = "Scott";
FName[39] = "Pamela";
MName[40] = "Frank";
FName[40] = "Nicole";
MName[41] = "Brandon";
FName[41] = "Katherine";
MName[42] = "Raymond";
FName[42] = "Virginia";
MName[43] = "Gregory";
FName[43] = "Catherine";
MName[44] = "Benjamin";
FName[44] = "Christine";
MName[45] = "Samuel";
FName[45] = "Samantha";
MName[46] = "Patrick";
FName[46] = "Debra";
MName[47] = "Alexander";
FName[47] = "Janet";
MName[48] = "Jack";
FName[48] = "Rachel";
MName[49] = "Dennis";
FName[49] = "Carolyn";
MName[50] = "Jerry";
FName[50] = "Emma";
MName[51] = "Tyler";
FName[51] = "Maria";
MName[52] = "Aaron";
FName[52] = "Heather";
MName[53] = "Henry";
FName[53] = "Diane";
MName[54] = "Douglas";
FName[54] = "Julie";
MName[55] = "Jose";
FName[55] = "Joyce";
MName[56] = "Peter";
FName[56] = "Evelyn";
MName[57] = "Adam";
FName[57] = "Frances";
MName[58] = "Zachary";
FName[58] = "Joan";
MName[59] = "Nathan";
FName[59] = "Christina";
MName[60] = "Walter";
FName[60] = "Kelly";
MName[61] = "Harold";
FName[61] = "Victoria";
MName[62] = "Kyle";
FName[62] = "Lauren";
MName[63] = "Carl";
FName[63] = "Martha";
MName[64] = "Arthur";
FName[64] = "Judith";
MName[65] = "Gerald";
FName[65] = "Cheryl";
MName[66] = "Roger";
FName[66] = "Megan";
MName[67] = "Keith";
FName[67] = "Andrea";
MName[68] = "Jeremy";
FName[68] = "Ann";
MName[69] = "Terry";
FName[69] = "Alice";
MName[70] = "Lawrence";
FName[70] = "Jean";
MName[71] = "Sean";
FName[71] = "Doris";
MName[72] = "Christian";
FName[72] = "Jacqueline";
MName[73] = "Albert";
FName[73] = "Kathryn";
MName[74] = "Joe";
FName[74] = "Hannah";
MName[75] = "Ethan";
FName[75] = "Olivia";
MName[76] = "Austin";
FName[76] = "Gloria";
MName[77] = "Jesse";
FName[77] = "Marie";
MName[78] = "Willie";
FName[78] = "Teresa";
MName[79] = "Billy";
FName[79] = "Sara";
MName[80] = "Bryan";
FName[80] = "Janice";
MName[81] = "Bruce";
FName[81] = "Julia";
MName[82] = "Jordan";
FName[82] = "Grace";
MName[83] = "Ralph";
FName[83] = "Judy";
MName[84] = "Roy";
FName[84] = "Theresa";
MName[85] = "Noah";
FName[85] = "Rose";
MName[86] = "Dylan";
FName[86] = "Beverly";
MName[87] = "Eugene";
FName[87] = "Denise";
MName[88] = "Wayne";
FName[88] = "Marilyn";
MName[89] = "Alan";
FName[89] = "Amber";
MName[90] = "Juan";
FName[90] = "Madison";
MName[91] = "Louis";
FName[91] = "Danielle";
MName[92] = "Russell";
FName[92] = "Brittany";
MName[93] = "Gabriel";
FName[93] = "Diana";
MName[94] = "Randy";
FName[94] = "Abigail";
MName[95] = "Philip";
FName[95] = "Jane";
MName[96] = "Harry";
FName[96] = "Natalie";
MName[97] = "Vincent";
FName[97] = "Lori";
MName[98] = "Bobby";
FName[98] = "Tiffany";
MName[99] = "Johnny";
FName[99] = "Alexis";
MName[100] = "Logan";
FName[100] = "Kayla";
LName[0] = "Smith";
LName[1] = "Johnson";
LName[2] = "Williams";
LName[3] = "Jones";
LName[4] = "Brown";
LName[5] = "Davis";
LName[6] = "Miller";
LName[7] = "Wilson";
LName[8] = "Moore";
LName[9] = "Taylor";
LName[10] = "Anderson";
LName[11] = "Thomas";
LName[12] = "Jackson";
LName[13] = "White";
LName[14] = "Harris";
LName[15] = "Martin";
LName[16] = "Thompson";
LName[17] = "Garcia";
LName[18] = "Martinez";
LName[19] = "Robinson";
LName[20] = "Clark";
LName[21] = "Rodriguez";
LName[22] = "Lewis";
LName[23] = "Lee";
LName[24] = "Walker";
LName[25] = "Hall";
LName[26] = "Allen";
LName[27] = "Young";
LName[28] = "Hernandez";
LName[29] = "King";
LName[30] = "Wright";
LName[31] = "Lopez";
LName[32] = "Hill";
LName[33] = "Scott";
LName[34] = "Green";
LName[35] = "Adams";
LName[36] = "Baker";
LName[37] = "Gonzalez";
LName[38] = "Nelson";
LName[39] = "Carter";
LName[40] = "Mitchell";
LName[41] = "Perez";
LName[42] = "Roberts";
LName[43] = "Turner";
LName[44] = "Phillips";
LName[45] = "Campbell";
LName[46] = "Parker";
LName[47] = "Evans";
LName[48] = "Edwards";
LName[49] = "Collins";
LName[50] = "Stewart";
LName[51] = "Sanchez";
LName[52] = "Morris";
LName[53] = "Rogers";
LName[54] = "Reed";
LName[55] = "Cook";
LName[56] = "Morgan";
LName[57] = "Bell";
LName[58] = "Murphy";
LName[59] = "Bailey";
LName[60] = "Rivera";
LName[61] = "Cooper";
LName[62] = "Richardson";
LName[63] = "Cox";
LName[64] = "Howard";
LName[65] = "Ward";
LName[66] = "Torres";
LName[67] = "Peterson";
LName[68] = "Gray";
LName[69] = "Ramirez";
LName[70] = "James";
LName[71] = "Watson";
LName[72] = "Brooks";
LName[73] = "Kelly";
LName[74] = "Sanders";
LName[75] = "Price";
LName[76] = "Bennett";
LName[77] = "Wood";
LName[78] = "Barnes";
LName[79] = "Ross";
LName[80] = "Henderson";
LName[81] = "Coleman";
LName[82] = "Jenkins";
LName[83] = "Long";
LName[84] = "Patterson";
LName[85] = "Hughes";
LName[86] = "Flores";
LName[87] = "Washington";
LName[88] = "Butler";
LName[89] = "Simmons";
LName[90] = "Foster";
LName[91] = "Gonzales";
LName[92] = "Bryant";
LName[93] = "Alexander";
LName[94] = "Russell";
LName[95] = "Griffin";
LName[96] = "Diaz";
LName[97] = "Hayes";
LName[98] = "Myers";
LName[99] = "Ford";
LName[100] = "Hamilton";
LName[101] = "Graham";
LName[102] = "Sullivan";
LName[103] = "Wallace";
LName[104] = "Woods";
LName[105] = "Cole";
LName[106] = "West";
LName[107] = "Jordan";
LName[108] = "Owens";
LName[109] = "Reynolds";
LName[110] = "Fisher";
LName[111] = "Ellis";
LName[112] = "Harrison";
LName[113] = "Gibson";
LName[114] = "Mcdonald";
LName[115] = "Cruz";
LName[116] = "Marshall";
LName[117] = "Ortiz";
LName[118] = "Gomez";
LName[119] = "Murray";
LName[120] = "Freeman";
LName[121] = "Wells";
LName[122] = "Webb";
LName[123] = "Simpson";
LName[124] = "Stevens";
LName[125] = "Tucker";
LName[126] = "Porter";
LName[127] = "Hunter";
LName[128] = "Hicks";
LName[129] = "Crawford";
LName[130] = "Henry";
LName[131] = "Boyd";
LName[132] = "Mason";
LName[133] = "Morales";
LName[134] = "Kennedy";
LName[135] = "Warren";
LName[136] = "Dixon";
LName[137] = "Ramos";
LName[138] = "Reyes";
LName[139] = "Burns";
LName[140] = "Gordon";
LName[141] = "Shaw";
LName[142] = "Holmes";
LName[143] = "Rice";
LName[144] = "Robertson";
LName[145] = "Hunt";
LName[146] = "Black";
LName[147] = "Daniels";
LName[148] = "Palmer";
LName[149] = "Mills";
LName[150] = "Nichols";
LName[151] = "Grant";
LName[152] = "Knight";
LName[153] = "Ferguson";
LName[154] = "Rose";
LName[155] = "Stone";
LName[156] = "Hawkins";
LName[157] = "Dunn";
LName[158] = "Perkins";
LName[159] = "Hudson";
LName[160] = "Spencer";
LName[161] = "Gardner";
LName[162] = "Stephens";
LName[163] = "Payne";
LName[164] = "Pierce";
LName[165] = "Berry";
LName[166] = "Matthews";
LName[167] = "Arnold";
LName[168] = "Wagner";
LName[169] = "Willis";
LName[170] = "Ray";
LName[171] = "Watkins";
LName[172] = "Olson";
LName[173] = "Carroll";
LName[174] = "Duncan";
LName[175] = "Snyder";
LName[176] = "Hart";
LName[177] = "Cunningham";
LName[178] = "Bradley";
LName[179] = "Lane";
LName[180] = "Andrews";
LName[181] = "Ruiz";
LName[182] = "Harper";
LName[183] = "Fox";
LName[184] = "Riley";
LName[185] = "Armstrong";
LName[186] = "Carpenter";
LName[187] = "Weaver";
LName[188] = "Greene";
LName[189] = "Lawrence";
LName[190] = "Elliott";
LName[191] = "Chavez";
LName[192] = "Sims";
LName[193] = "Austin";
LName[194] = "Peters";
LName[195] = "Kelley";
LName[196] = "Franklin";
LName[197] = "Lawson";
LName[198] = "Perry";
LName[199] = "Powell";

/*
You'll generate the same names over and over again if you
rely on random_range() so this uses time passed to add
more random-ness to the code
*/

var tempN1, tempN2;

tempN1 = random_range(0,100);
if(tempN1<0){
	tempN1 = 101-tempN1;
}
if(tempN1>100){
	tempN1 = 0+(tempN1-101);
}
tempN2 = random_range(0,199);
if(tempN2<0){
	tempN2 = 200-tempN2;
}
if(tempN2>199){
	tempN2 = 0+(tempN2-200);
}

//Return Choices
if(argument[1]=="Last"){
	return(LName[tempN2]);
}

//get random sex
if (argument[0] == "R") {
	var sex = ["M","F"];
	argument[0] = sex[irandom_range(0,1)];
}

if(argument[0]=="F"){
	if(argument[1]=="Full"){
		return(string(FName[tempN1]+" "+LName[tempN2]));
	}
	if(argument[1]=="First"){
		return(FName[tempN1]);
	}
}

if(argument[0]=="M"){
	if(argument[1]=="Full"){
		return(string(MName[tempN1]+" "+LName[tempN2]));
	}
	if(argument[1]=="First"){
		return(MName[tempN1]);
	}
}